=== bhagwatpalve/WTL-Assignment/Assignment_3/employee.dtd
<!ELEMENT Employee (Employee_Info+)>
<!ELEMENT Employee_Info (Emp_ID,Emp_Name,Emp_Designation,Emp_Salary,Emp_MobNo,Emp_Email)>
<!ELEMENT Emp_ID (#PCDATA)>
<!ELEMENT Emp_Name (#PCDATA)>
<!ELEMENT Emp_Designation (#PCDATA)>
<!ELEMENT Emp_Salary (#PCDATA)>
<!ELEMENT Emp_MobNo (#PCDATA)>
<!ELEMENT Emp_Email (#PCDATA)>

=== bhagwatpalve/WTL-Assignment/Assignment_3/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl" ?>
<!DOCTYPE Employee SYSTEM "Employee.dtd">

<Employee>
    <Employee_Info>
        <Emp_ID>7369</Emp_ID>
        <Emp_Name>Smith</Emp_Name>
        <Emp_Designation>Clerk</Emp_Designation>
        <Emp_Salary>15000</Emp_Salary>
        <Emp_MobNo>9560304431</Emp_MobNo>
        <Emp_Email>smith@gmail.com</Emp_Email>
    </Employee_Info>

    <Employee_Info>
        <Emp_ID>7439</Emp_ID>
        <Emp_Name>Allen</Emp_Name>
        <Emp_Designation>Salesman</Emp_Designation>
        <Emp_Salary>14000</Emp_Salary>
        <Emp_MobNo>9840305411</Emp_MobNo>
        <Emp_Email>allen@gmail.com</Emp_Email>
    </Employee_Info>

    <Employee_Info>
        <Emp_ID>7566</Emp_ID>
        <Emp_Name>Joe</Emp_Name>
        <Emp_Designation>Manager</Emp_Designation>
        <Emp_Salary>50000</Emp_Salary>
        <Emp_MobNo>9965504411</Emp_MobNo>
        <Emp_Email>joe@gmail.com</Emp_Email>
    </Employee_Info>

    <Employee_Info>
        <Emp_ID>7834</Emp_ID>
        <Emp_Name>John</Emp_Name>
        <Emp_Designation>Analyst</Emp_Designation>
        <Emp_Salary>30000</Emp_Salary>
        <Emp_MobNo>9168374461</Emp_MobNo>
        <Emp_Email>john@gmail.com</Emp_Email>
    </Employee_Info>

    <Employee_Info>
        <Emp_ID>7369</Emp_ID>
        <Emp_Name>Adam</Emp_Name>
        <Emp_Designation>CEO</Emp_Designation>
        <Emp_Salary>75000</Emp_Salary>
        <Emp_MobNo>9655443311</Emp_MobNo>
        <Emp_Email>adam@gmail.com</Emp_Email>
    </Employee_Info>

</Employee>
